-- Additive migration: no booking, shift, identity or score data is changed.
BEGIN;
SET LOCAL search_path TO "ynu-shooting";
CREATE TABLE IF NOT EXISTS wechat_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(16) NOT NULL,
    target_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    template_id VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    scheduled_at TIMESTAMP(6) NOT NULL,
    starts_at TIMESTAMP(6) NOT NULL,
    next_attempt_at TIMESTAMP(6) NOT NULL,
    subscribed_at TIMESTAMP(6) NOT NULL,
    claimed_at TIMESTAMP(6),
    sent_at TIMESTAMP(6),
    attempts INTEGER NOT NULL,
    last_code VARCHAR(64),
    CONSTRAINT uk_reminder_target UNIQUE (kind,target_id)
);
CREATE INDEX IF NOT EXISTS idx_reminder_due ON wechat_reminders(status,next_attempt_at);
COMMENT ON COLUMN wechat_reminders.target_id IS 'Logical reference to bookings.id or admin_schedules.id; retained after shift deletion';
COMMENT ON COLUMN wechat_reminders.user_id IS 'Logical reference to users.id; revalidated against live booking/shift before sending';
ALTER TABLE wechat_reminders OWNER TO ynu_app;
COMMIT;
