-- Additive migration. Existing scores remain one final score per training session.
BEGIN;
SET LOCAL search_path TO "ynu-shooting";
CREATE TABLE IF NOT EXISTS score_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_session_id BIGINT NOT NULL CONSTRAINT fk_score_attempts__training_session_id__training_sessions REFERENCES training_sessions(id),
    request_key VARCHAR(64) NOT NULL,
    total_score DOUBLE PRECISION NOT NULL CHECK (total_score >= 0 AND total_score <= 600),
    group_totals TEXT NOT NULL,
    shot_scores TEXT NOT NULL,
    group_scores TEXT NOT NULL,
    recorded_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_score_attempt_request UNIQUE (training_session_id, request_key)
);
ALTER TABLE score_attempts OWNER TO ynu_app;
COMMIT;
