-- PostgreSQL 14+：在 DataGrip 中选择目标数据库，执行整个文件。
-- 与当前 13 个 JPA 实体对应；统一使用 "ynu-shooting" schema。
-- 只创建缺失的表，不删除数据；不会升级已存在但结构过旧的表。
-- 执行成功后，再运行同目录 init.sql（仅本地演示数据）。
BEGIN;
CREATE SCHEMA IF NOT EXISTS "ynu-shooting";
SET LOCAL search_path TO "ynu-shooting";

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openid VARCHAR(255) NOT NULL UNIQUE,
    nickname VARCHAR(100),
    avatar_url VARCHAR(255),
    role VARCHAR(255) NOT NULL CHECK (role IN ('student', 'admin', 'superadmin')),
    profile_status VARCHAR(255) NOT NULL CHECK (profile_status IN ('pending', 'completed')),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS profiles (
    user_id BIGINT PRIMARY KEY CONSTRAINT fk_profiles__user_id__users REFERENCES users(id),
    real_name VARCHAR(255) NOT NULL,
    student_no VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL,
    gender VARCHAR(1),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(255) NOT NULL CHECK (type IN ('rifle', 'pistol')),
    status VARCHAR(255) NOT NULL CHECK (status IN ('IDLE', 'BOOKED', 'IN_USE', 'MAINTENANCE', 'DISABLED')),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL CONSTRAINT fk_bookings__user_id__users REFERENCES users(id),
    device_id BIGINT NOT NULL CONSTRAINT fk_bookings__device_id__devices REFERENCES devices(id),
    slot_date VARCHAR(255) NOT NULL,
    slot_id VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL CHECK (status IN ('BOOKED', 'CHECKED_IN', 'IN_USE', 'COMPLETED', 'CANCELLED', 'NO_SHOW')),
    booked_at TIMESTAMP(6) NOT NULL,
    checked_in_at TIMESTAMP(6),
    started_at TIMESTAMP(6),
    ended_at TIMESTAMP(6),
    cancel_reason VARCHAR(255),
    occupied_device_slot VARCHAR(255) UNIQUE,
    occupied_user_slot VARCHAR(255) UNIQUE
);

CREATE TABLE IF NOT EXISTS training_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL UNIQUE CONSTRAINT fk_training_sessions__booking_id__bookings REFERENCES bookings(id),
    user_id BIGINT NOT NULL CONSTRAINT fk_training_sessions__user_id__users REFERENCES users(id),
    device_id BIGINT NOT NULL CONSTRAINT fk_training_sessions__device_id__devices REFERENCES devices(id),
    mode VARCHAR(255) NOT NULL CHECK (mode IN ('final_', 'qualifying')),
    started_at TIMESTAMP(6),
    ended_at TIMESTAMP(6),
    actual_duration_min INTEGER,
    resume_started_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_session_id BIGINT NOT NULL CONSTRAINT fk_scores__training_session_id__training_sessions REFERENCES training_sessions(id),
    mode VARCHAR(255) NOT NULL CHECK (mode IN ('final_', 'qualifying')),
    total_score DOUBLE PRECISION NOT NULL,
    group_scores TEXT NOT NULL,
    shot_scores TEXT NOT NULL,
    group_spec TEXT NOT NULL,
    shot_count INTEGER NOT NULL,
    x_count INTEGER,
    recorded_by_user_id BIGINT CONSTRAINT fk_scores__recorded_by_user_id__users REFERENCES users(id),
    recorded_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_score_session_mode UNIQUE (training_session_id,mode)
);

CREATE TABLE IF NOT EXISTS admin_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT NOT NULL CONSTRAINT fk_admin_schedules__admin_user_id__users REFERENCES users(id),
    slot_date VARCHAR(255) NOT NULL,
    slot_id VARCHAR(255) NOT NULL,
    arrived_at TIMESTAMP(6),
    departed_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_admin_schedule_slot UNIQUE (admin_user_id, slot_date, slot_id),
    CONSTRAINT ck_admin_schedule_attendance CHECK (
        departed_at IS NULL OR (arrived_at IS NOT NULL AND departed_at >= arrived_at)
    )
);

CREATE TABLE IF NOT EXISTS user_availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL CONSTRAINT fk_user_availability__user_id__users REFERENCES users(id),
    slot_date VARCHAR(255) NOT NULL,
    slot_id VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS cancellation_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT NOT NULL CONSTRAINT fk_cancellation_log__booking_id__bookings REFERENCES bookings(id),
    user_id BIGINT NOT NULL CONSTRAINT fk_cancellation_log__user_id__users REFERENCES users(id),
    reason VARCHAR(255) NOT NULL,
    level VARCHAR(255) NOT NULL CHECK (level IN ('free', 'late', 'near_no_show')),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS no_show_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL CONSTRAINT fk_no_show_records__user_id__users REFERENCES users(id),
    booking_id BIGINT NOT NULL CONSTRAINT fk_no_show_records__booking_id__bookings REFERENCES bookings(id),
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_user_id BIGINT CONSTRAINT fk_audit_log__admin_user_id__users REFERENCES users(id),
    action VARCHAR(255) NOT NULL,
    target_user_id BIGINT,
    detail TEXT,
    created_at TIMESTAMP(6) NOT NULL
);

-- DataGrip 可直接显示字段注释和外键目标。
COMMENT ON COLUMN admin_schedules.admin_user_id IS '外键 -> users.id；值班教员用户';
COMMENT ON COLUMN audit_log.admin_user_id IS '外键 -> users.id；操作管理员用户';
COMMENT ON COLUMN bookings.device_id IS '外键 -> devices.id；关联记录';
COMMENT ON COLUMN bookings.user_id IS '外键 -> users.id；关联记录';
COMMENT ON COLUMN cancellation_log.booking_id IS '外键 -> bookings.id；关联记录';
COMMENT ON COLUMN cancellation_log.user_id IS '外键 -> users.id；关联记录';
COMMENT ON COLUMN no_show_records.booking_id IS '外键 -> bookings.id；关联记录';
COMMENT ON COLUMN no_show_records.user_id IS '外键 -> users.id；关联记录';
COMMENT ON COLUMN profiles.user_id IS '外键 -> users.id；所属用户；同时为本表主键（一对一档案）';
COMMENT ON COLUMN scores.recorded_by_user_id IS '外键 -> users.id；录分人用户';
COMMENT ON COLUMN scores.training_session_id IS '外键 -> training_sessions.id；对应训练记录';
COMMENT ON COLUMN training_sessions.booking_id IS '外键 -> bookings.id；关联记录';
COMMENT ON COLUMN training_sessions.device_id IS '外键 -> devices.id；关联记录';
COMMENT ON COLUMN training_sessions.user_id IS '外键 -> users.id；关联记录';
COMMENT ON COLUMN user_availability.user_id IS '外键 -> users.id；关联记录';
COMMENT ON COLUMN audit_log.target_user_id IS '逻辑引用 -> users.id；历史操作目标标识，不设数据库外键约束';
COMMENT ON COLUMN admin_schedules.slot_id IS '时间片代码 S1-S6，对应代码中的 Slot 枚举；不是数据库外键';
COMMENT ON COLUMN bookings.slot_id IS '时间片代码 S1-S6，对应代码中的 Slot 枚举；不是数据库外键';
COMMENT ON COLUMN user_availability.slot_id IS '时间片代码 S1-S6，对应代码中的 Slot 枚举；不是数据库外键';

CREATE TABLE IF NOT EXISTS score_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_session_id BIGINT NOT NULL CONSTRAINT fk_score_attempts__training_session_id__training_sessions REFERENCES training_sessions(id),
    mode VARCHAR(255) NOT NULL CONSTRAINT ck_score_attempt_mode CHECK (mode IN ('final_', 'qualifying')),
    request_key VARCHAR(64) NOT NULL,
    total_score DOUBLE PRECISION NOT NULL CHECK (total_score >= 0 AND total_score <= 600),
    group_totals TEXT NOT NULL,
    shot_scores TEXT NOT NULL,
    group_scores TEXT NOT NULL,
    recorded_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_score_attempt_request UNIQUE (training_session_id, request_key)
);

CREATE TABLE IF NOT EXISTS wechat_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind VARCHAR(16) NOT NULL,
    target_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    template_id VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL,
    scheduled_at TIMESTAMP(6) NOT NULL,
    starts_at TIMESTAMP(6) NOT NULL,
    next_attempt_at TIMESTAMP(6) NOT NULL,
    subscribed_at TIMESTAMP(6) NOT NULL,
    claimed_at TIMESTAMP(6),
    sent_at TIMESTAMP(6),
    attempts INTEGER NOT NULL,
    last_code VARCHAR(64),
    CONSTRAINT uk_reminder_target UNIQUE (kind,target_id)
);
CREATE INDEX IF NOT EXISTS idx_reminder_due ON wechat_reminders(status,next_attempt_at);
COMMENT ON COLUMN wechat_reminders.target_id IS 'Logical reference to bookings.id or admin_schedules.id; retained after shift deletion';
COMMENT ON COLUMN wechat_reminders.user_id IS 'Logical reference to users.id; revalidated against live booking/shift before sending';

COMMIT;
